services:
  phpmyadmin:
    image: phpmyadmin:5.2.2-apache
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      database:
        condition: service_healthy
    links:
      - database:db
    networks:
      - private
