
services:
###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:10.11.11-jammy
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - equisplit_mdb_data:/var/lib/mysql
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  equisplit_mdb_data:
###< doctrine/doctrine-bundle ###
